version: "3"

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-stream
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "1234"
  
  backend:
    build:
      context: ./backend
    command: python -m flask run --host=127.0.0.1 --port=5000
    ports:
      - 5050:5000
    volumes:
      - ./backend/:/backend/
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: ./frontend
    command: [ "yarn", "start" ]
    ports:
      - 80:3000
    volumes:
      - ./frontend/:/frontend
      - ./frontend/node_modules/:/frontend/node_modules
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://127.0.0.1:5000
    tty: true

#volumes:
 # postgres_data_dev: null
